language: c

deploy:
  provider: pages
  local_dir: out
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  # Token will be changed in future
  on:
    branch: master

services:
  - docker

sudo: required

before_script:
  # download previous version
  - wget -q https://akuhak.github.io/test_build/opl.zip -O out/opl_old.zip
  - wget -q https://akuhak.github.io/test_build/opl.commit -O out/opl_old.commit
  - wget -q https://akuhak.github.io/test_build/boot.elf -O out/boot_old.elf
  - wget -q https://akuhak.github.io/test_build/ule.commit -O out/ule_old.commit
  - wget -q https://akuhak.github.io/test_build/fceu-packed.elf -O out/fceu-packed_old.elf
  - wget -q https://akuhak.github.io/test_build/fc.commit -O out/fc_old.commit
  - wget -q https://akuhak.github.io/test_build/gs.commit -O out/gs_old.commit

  # Get docker image
  - docker pull akuhak/ps2toolchain:latest
  - docker ps

  # Run DOCKER, run!
  - docker run -d akuhak/ps2toolchain bash -c "while true; do sleep 5; done" > container_id

  # Configure ps2sdk
  - docker exec -t $(cat container_id) bash -c "ls -l"
  - docker exec -t $(cat container_id) bash -c "cd /; git clone https://github.com/ps2dev/ps2sdk"
  - docker exec -t $(cat container_id) bash -c "cd /ps2sdk/; make install --silent"
  - docker exec -t $(cat container_id) bash -c "cd /ps2sdk/; git log --pretty=format:'%h' -n 1 > ps2sdk.commit"
  - docker exec -t $(cat container_id) bash -c "cd /ps2sdk/; echo '</td><td>&nbsp;' >> ps2sdk.commit"
  - docker exec -t $(cat container_id) bash -c "cd /ps2sdk/; git log -1 --format='%at' | xargs -I{} date -d @{} +%F_%T >> ps2sdk.commit"
  - docker cp $(cat container_id):/ps2sdk/ps2sdk.commit $TRAVIS_BUILD_DIR/out/ps2sdk.commit

  # installing ports
  - docker exec -t $(cat container_id) bash -c "cd /; git clone https://github.com/ps2dev/ps2sdk-ports"
  - docker exec -t $(cat container_id) bash -c "cd /ps2sdk-ports/zlib/; make install"
  - docker exec -t $(cat container_id) bash -c "cd /ps2sdk-ports/libpng/; make install"
  - docker exec -t $(cat container_id) bash -c "cd /ps2sdk-ports/libjpeg/; make install"
  - docker exec -t $(cat container_id) bash -c "cd /ps2sdk-ports/freetype-2.9.1/; bash ./SetupPS2.sh"
  - docker exec -t $(cat container_id) bash -c "cd /ps2sdk-ports/; git log --pretty=format:'%h' -n 1 > ps2sdk-ports.commit"
  - docker exec -t $(cat container_id) bash -c "cd /ps2sdk-ports/; echo '</td><td>&nbsp;' >> ps2sdk-ports.commit"
  - docker exec -t $(cat container_id) bash -c "cd /ps2sdk-ports/; git log -1 --format='%at' | xargs -I{} date -d @{} +%F_%T >> ps2sdk-ports.commit"
  - docker cp $(cat container_id):/ps2sdk-ports/ps2sdk-ports.commit $TRAVIS_BUILD_DIR/out/ps2sdk-ports.commit

  # installing ps2eth
  - docker exec -t $(cat container_id) bash -c "cd /; git clone https://github.com/ps2dev/ps2eth"
  # Ugly hack cause inside this bash no support for PS2DEV
  - docker exec -t $(cat container_id) bash -c "cd /ps2eth/; make; mkdir -p /ps2dev/ps2eth"
  - docker exec -t $(cat container_id) bash -c "cd /ps2eth/; mkdir -p /ps2dev/ps2eth/smap /ps2dev/ps2eth/smap-linux"
  - docker exec -t $(cat container_id) bash -c "cp -f /ps2eth/smap/ps2smap.irx /ps2dev/ps2eth/smap/"
  - docker exec -t $(cat container_id) bash -c "cp -f /ps2eth/smap-linux/ps2smap.irx /ps2dev/ps2eth/smap-linux/"

  # installing gsKit
  - docker exec -t $(cat container_id) bash -c "cd /; git clone https://github.com/ps2dev/gsKit"
  - docker exec -t $(cat container_id) bash -c "cd /gsKit/; bash ./setup.sh"
  - docker exec -t $(cat container_id) bash -c "cd /gsKit/; git log --pretty=format:'%h' -n 1 > gs.commit"
  - docker exec -t $(cat container_id) bash -c "cd /gsKit/; echo '</td><td>&nbsp;' >> gs.commit"
  - docker exec -t $(cat container_id) bash -c "cd /gsKit/; git log -1 --format='%at' | xargs -I{} date -d @{} +%F_%T >> gs.commit"
  - docker cp $(cat container_id):/gsKit/gs.commit $TRAVIS_BUILD_DIR/out/gs.commit

  # installing ps2-packer
  - docker exec -t $(cat container_id) bash -c "cd /; git clone https://github.com/ps2dev/ps2-packer"
  - docker exec -t $(cat container_id) bash -c "cd /ps2-packer/; make install"
  - docker exec -t $(cat container_id) bash -c "cd /ps2-packer/; git log --pretty=format:'%h' -n 1 > ps2packer.commit"
  - docker exec -t $(cat container_id) bash -c "cd /ps2-packer/; echo '</td><td>&nbsp;' >> ps2packer.commit"
  - docker exec -t $(cat container_id) bash -c "cd /ps2-packer/; git log -1 --format='%at' | xargs -I{} date -d @{} +%F_%T >> ps2packer.commit"
  - docker cp $(cat container_id):/ps2-packer/ps2packer.commit $TRAVIS_BUILD_DIR/out/ps2packer.commit

  - docker exec -t $(cat container_id) bash -c "cd /ps2toolchain/; git log --pretty=format:'%h' -n 1 > ps2toolchain.commit"
  - docker exec -t $(cat container_id) bash -c "cd /ps2toolchain/; echo '</td><td>&nbsp;' >> ps2toolchain.commit"
  - docker exec -t $(cat container_id) bash -c "cd /ps2toolchain/; git log -1 --format='%at' | xargs -I{} date -d @{} +%F_%T >> ps2toolchain.commit"
  - docker cp $(cat container_id):/ps2toolchain/ps2toolchain.commit $TRAVIS_BUILD_DIR/out/ps2toolchain.commit

script:
  # Fceumm-PS2
  - docker exec -t $(cat container_id) bash -c "cd /; git clone https://github.com/AKuHAK/Fceumm-PS2"
  - docker exec -t $(cat container_id) bash -c "cd /Fceumm-PS2/; git log --pretty=format:'%h' -n 1 > fc.commit"
  - docker cp $(cat container_id):/Fceumm-PS2/fc.commit $TRAVIS_BUILD_DIR/out/fc.commit
  - echo "</td><td>&nbsp;" >> $TRAVIS_BUILD_DIR/out/fc.commit
  - date -r $TRAVIS_BUILD_DIR/.travis.yml +%F_%T >> $TRAVIS_BUILD_DIR/out/fc.commit
  - docker exec -t $(cat container_id) bash -c "cd /Fceumm-PS2/; make -f Makefile.ps2 CDSUPPORT=1"
  - docker cp $(cat container_id):/Fceumm-PS2/fceu-packed.elf $TRAVIS_BUILD_DIR/out/fceu-packed.elf
  # uLaunchELF
  - docker exec -t $(cat container_id) bash -c "cd /; git clone https://github.com/AKuHAK/uLaunchELF"
  - docker exec -t $(cat container_id) bash -c "cd /uLaunchELF/; git log --pretty=format:'%h' -n 1 > ule.commit"
  - docker cp $(cat container_id):/uLaunchELF/ule.commit $TRAVIS_BUILD_DIR/out/ule.commit
  - echo "</td><td>&nbsp;" >> $TRAVIS_BUILD_DIR/out/ule.commit
  - date -r $TRAVIS_BUILD_DIR/.travis.yml +%F_%T >> $TRAVIS_BUILD_DIR/out/ule.commit
  - docker exec -t $(cat container_id) bash -c "cd /uLaunchELF/; make"
  - docker cp $(cat container_id):/uLaunchELF/BOOT.ELF $TRAVIS_BUILD_DIR/out/boot.elf
  # OPL
  - mkdir -p $TRAVIS_BUILD_DIR/Open-PS2-Loader/out/OPL/
  - docker exec -t $(cat container_id) bash -c "cd /; git clone https://github.com/ifcaro/Open-PS2-Loader"
  - docker exec -t $(cat container_id) bash -c "cd /Open-PS2-Loader/; git log --pretty=format:'%h' -n 1 > opl.commit"
  - docker cp $(cat container_id):/Open-PS2-Loader/opl.commit $TRAVIS_BUILD_DIR/out/opl.commit
  - echo "</td><td>&nbsp;" >> $TRAVIS_BUILD_DIR/out/opl.commit
  - date -r $TRAVIS_BUILD_DIR/.travis.yml +%F_%T >> $TRAVIS_BUILD_DIR/out/opl.commit
  - mkdir -p $TRAVIS_BUILD_DIR/Open-PS2-Loader/out/OPL/
  - docker exec -t $(cat container_id) bash -c "cd /Open-PS2-Loader/; make clean; make"
  - docker cp $(cat container_id):/Open-PS2-Loader/OPNPS2LD.ELF $TRAVIS_BUILD_DIR/Open-PS2-Loader/out/OPL/
  - docker exec -t $(cat container_id) bash -c "cd /Open-PS2-Loader/; make clean; make release"
  - docker exec -t $(cat container_id) bash -c "cd /Open-PS2-Loader/; bash ./make_changelog.sh"
  - docker cp $(cat container_id):/Open-PS2-Loader/DETAILED_CHANGELOG $TRAVIS_BUILD_DIR/Open-PS2-Loader/out/OPL/
  - docker cp $(cat container_id):/Open-PS2-Loader/OPNPS2LD.ELF $TRAVIS_BUILD_DIR/Open-PS2-Loader/out/OPNPS2LD-release.ELF
  - cd $TRAVIS_BUILD_DIR/Open-PS2-Loader/
  - zip -r opl.zip out/
  - cp -f opl.zip $TRAVIS_BUILD_DIR/out/opl.zip

  - cd $TRAVIS_BUILD_DIR
  - mv out/index.html out/index.html.bak
  - cat part1.html out/ule.commit ule_new_old.html out/ule_old.commit ule_opl.html out/opl.commit opl_new_old.html out/opl_old.commit opl_fc.html out/fc.commit fc_new_old.html out/fc_old.commit fc_ps2toolchain.html out/ps2toolchain.commit ps2toolchain_ps2sdk.html out/ps2sdk.commit ps2sdk_gs.html out/gs.commit gs_new_old.html out/gs_old.commit gs_ps2sdk-ports.html out/ps2sdk-ports.commit ps2sdk-ports_ps2packer.html out/ps2packer.commit ps2packer_end.html > out/index.html
  - cd $TRAVIS_BUILD_DIR
