deploy:
  provider: pages
  local_dir: out
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
    
sudo: required

install:
 ## Dependencies
 - sudo apt-get install -yqqq gcc-4.4 patch wget make git libc6-dev zlib1g zlib1g-dev libucl1 libucl-dev

before_script:
- wget https://akuhak.github.io/test_build/opl.elf -o out/opl_old.elf
- wget https://akuhak.github.io/test_build/opl.time -o out/opl_old.time
- wget https://akuhak.github.io/test_build/boot.elf -o out/boot_old.elf
- wget https://akuhak.github.io/test_build/boot.time -o out/boot_old.time
# setting environment
- export PS2DEV=${HOME}/ps2dev
- export PS2SDK=${PS2DEV}/ps2sdk
- export PATH=${PATH}:${PS2DEV}/bin:${PS2DEV}/ee/bin:${PS2DEV}/iop/bin:${PS2DEV}/dvp/bin:${PS2SDK}/bin
# installing ps2toolchain (without ps2sdk and ps2link)
- git clone https://github.com/ps2dev/ps2toolchain.git
- cd ps2toolchain/
# scripts are silenced cause log will be enormous if we will see all output from toolchain setup
- bash ./toolchain.sh 1 > /tmp/PS2TOOLCHAIN1.log 2>&1
- bash ./toolchain.sh 2 > /tmp/PS2TOOLCHAIN2.log 2>&1
- bash ./toolchain.sh 3 > /tmp/PS2TOOLCHAIN3.log 2>&1
- bash ./toolchain.sh 4 > /tmp/PS2TOOLCHAIN4.log 2>&1
- cd $TRAVIS_BUILD_DIR
# installing ps2sdk
- git clone https://github.com/ps2dev/ps2sdk.git
- cd ps2sdk
- make -j2 install --silent
- cd $TRAVIS_BUILD_DIR
# installing ps2eth
- git clone https://github.com/ps2dev/ps2eth.git
- cd ps2eth
- make
- mkdir -p $PS2DEV/ps2eth
- tar c `find . -name \*irx` | tar x -C $PS2DEV/ps2eth
- cd $TRAVIS_BUILD_DIR
- git clone https://github.com/ps2dev/ps2sdk-ports.git
# installing ports
- cd ps2sdk-ports
- make install -C libjpeg
- make install -C zlib
- make install -C libpng
- cd freetype-2.4.12
- bash ./Setup.sh
- cd $TRAVIS_BUILD_DIR
# installing gsKit
- export GSKIT=${PS2DEV}/gsKit
- git clone https://github.com/ps2dev/gsKit.git
- cd gsKit/
- bash ./setup.sh
- cd $TRAVIS_BUILD_DIR
# installing ps2-packer
- git clone https://github.com/ps2dev/ps2-packer.git
- cd ps2-packer
- make install

script:
 - cd $TRAVIS_BUILD_DIR
 - git clone https://github.com/AKuHAK/uLaunchELF
 - cd uLaunchELF
 - make
 - git log --pretty=format:'%h' -n 1 > $TRAVIS_BUILD_DIR/out/ule.commit
 - date -r .travis.yml +%F_%T > $TRAVIS_BUILD_DIR/out/ule.time
 - cp -f ULE.ELF $TRAVIS_BUILD_DIR/out/boot.elf
 - cd $TRAVIS_BUILD_DIR
 - git clone https://github.com/AKuHAK/Open-PS2-Loader
 - cd Open-PS2-Loader
 - make
 - ls -l
 - git log --pretty=format:'%h' -n 1 > $TRAVIS_BUILD_DIR/out/opl.commit
 - date -r .travis.yml +%F_%T > $TRAVIS_BUILD_DIR/out/opl.time
 - cp -f OPNPS2LD.ELF $TRAVIS_BUILD_DIR/out/opl.elf
 - cd $TRAVIS_BUILD_DIR
